spring.application.name=pdv
spring.datasource.url=jdbc:mysql://localhost:3306/pdv_mercadinho?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=47557192
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
